POST http://localhost:{{serverPort}}/otp/register-client
Accept: application/json
Content-Type: application/json

"sebs-client-1"

###
# @name get
GET http://localhost:{{serverPort}}/otp
Accept: application/json
Content-Type: application/json

###
# @name refresh
POST http://localhost:{{serverPort}}/otp/refresh
Accept: application/json
Content-Type: application/json

###
# @name use
POST http://localhost:{{serverPort}}/otp/use
Accept: application/json
Content-Type: application/json

{
   "clientId": "\"sebs-client-1\"",
   "oneTimePassword": "131880"
}
